### ISSUE TITLE
[Compat-Issue] GregTech obligatorily require Tinkers' Construct and EnergyControl

### ISSUE THREAD

**Issue by gatoborrachon** [Su5eD/GregTech-Experimental#23]
Sorry for being late, i had no time until now

**Describe the bug**
I decided to see if i can run GregTechExperimental 1.0-29+IC2 only and i discovered that GregTechExperimental 1.0-29 crashes if it doesn't detect Tinkers' Construct and EnergyControl.

**Does this bug cause a crash?**
Tinkers' Construct: https://pastebin.com/Qv1hJUFk
Energy Control: https://pastebin.com/FnJF5rZJ

**Side**
i'm not sure, but i guess it affect both (ir server side mainly)

**To Reproduce**
1. Install GregTechExperimental 1.0-29 and IC2
2. Try to launch the game
3. See error

**Expected behavior**  
Not a Crash

**Additional context**  
This is not related to the issue, but wtf, i can't believe how you was able to implement the tools so nicely with other mods (for example HBM's Nuclear Tech Mod, that mod add hardcoded crafting recipes that GregTech succesfully changed).

There are still "issues" with some mods (they register an easier recipe to make a rod), mainly Jaopca and Advanced Rocketry, but i can fix that using Crafttweaker, i just want to say this.

**Comment by Su5eD** [comment]
Fixed the Tinkers crash, I forgot to add `@Optional` to a method
> gregtechmod-1.0-28.jar

According to the crash report, you were running GTE 1.0-28, which contains the bug described in issue #21. Upgrading should solve it.

**Comment by Su5eD** [comment]
> This is not related to the issue, but wtf, i can't believe how you was able to implement the tools so nicely with other mods (for example HBM's Nuclear Tech Mod, that mod add hardcoded crafting recipes that GregTech succesfully changed).

This is done by dynamic recipes. I scan all OreDictionary entries, and add recipes depending on their type. Good to hear it works

> There are still "issues" with some mods (they register an easier recipe to make a rod), mainly Jaopca and Advanced Rocketry, but i can fix that using Crafttweaker, i just want to say this.

Yeah, it can happen. Even though I want to add compat for other mods in the future (such as EnderIO or IE), I'll never be able to cover all the mods as there's too many of them. I'm leaving this up to modpack makers to solve

**Comment by gatoborrachon** [comment]
> According to the crash report, you were running GTE 1.0-28, which contains the bug described in issue #21. Upgrading should solve it.

mmm, you are right, but glad to see that both issues are fixed

> This is done by dynamic recipes. I scan all OreDictionary entries, and add recipes depending on their type. Good to hear it works

yeah i thought that it must be something dynamic, but you know, when something can go wrong, it will go wrong, or at least that i thought at the start

> I'm leaving this up to modpack makers to solve

ok, no problem
