### ISSUE TITLE
Recipe Handlers being registered multiple times 

### ISSUE THREAD

**Issue by CrossVas** [Su5eD/GregTech-Experimental#36]
### Describe the bug

TITLE

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Install GT + Deps
2. Install JEI
3. Look for recipes
...

### Logs

https://paste.ubuntu.com/p/h5hHx4y6wF/

### Additional context

<img width="388" alt="image" src="https://user-images.githubusercontent.com/25727222/152492388-cf2f2172-0e3a-44be-ad7a-348fe8d940fa.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/25727222/152492431-ba6ee6c9-bb56-4e42-bfb8-f1053e4aed6f.png">

**Comment by Su5eD** [comment]
Haven't been able to reproduce this unfortunately. Can you try again with the latest version?

**Comment by CrossVas** [comment]
It seems to happen occasionally on the version stated above (in the log). No occurrence on the latest version. Issue can be closed.
