### ISSUE TITLE
Aluminium Ore smelting prevention

### ISSUE THREAD

**Issue by jamesjimmy88** [Su5eD/GregTech-Experimental#51]
### Describe the solution you'd like

If a mod that adds aluminium ore (like Thermal Expansion) is present, you can completely bypass the Industrial Blast Furnace, since this recipe gets added (the output ingot is this mod's)
![2023-03-25_16 36 48](https://user-images.githubusercontent.com/58559532/227727180-42e61b0a-d77f-4f3c-ab7f-38b7db0c3a51.png)
I tried disabling it with CraftTweaker, but it didn't work, both with and without specifying the gregtechmod loader

**Comment by CrossVas** [comment]
In _config/GregTech/DynamicConfig.cfg_ under **smelting** section (L164) there is an entry for **B:tile.thermalfoundation.ore.aluminum.name** (L474). Setting this to false disable GT smelting recipe. The other (TE furnace, induction smelter) recipes can be removeed using CraftTweaker.

**Comment by jamesjimmy88** [comment]
Holy crap, how did I miss that...
This fixes everything, thank you.
